import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
// Generated by build/build_fonts.py - must load before styles.css, which
// consumes the --font-* variables these faces define.
import './fonts.css';
import './styles.css';
import './components/styles-components.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);